### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by Nxys** [zxystd/AthBluetoothFirmware#2]
使用1.0.0版本里的驱动，无法启动系统了

**Comment by shaizu** [comment]
yes I can't start my system also

**Comment by zxystd** [comment]
show me the kp log.

**Comment by whatnameisit** [comment]
[opencore-2020-10-12-135846.txt](https://github.com/zxystd/AthBluetoothFirmware/files/5365588/opencore-2020-10-12-135846.txt)
![IMG_2094](https://user-images.githubusercontent.com/47713349/95755674-a7f4a300-0cdf-11eb-9c6d-c14200752039.JPG)
Thanks

**Comment by htpcrig** [comment]
Any update on this. Im having the exact issue too

**Comment by lulujyc** [comment]
https://xsggx.xiaosg.workers.dev/AR9565/ar9565%E8%93%9D%E7%89%99%E9%A9%B1%E5%8A%A8.zip

**Comment by DaxSosa** [comment]
> https://xsggx.xiaosg.workers.dev/AR9565/ar9565%E8%93%9D%E7%89%99%E9%A9%B1%E5%8A%A8.zip
> 
> This version of the kext fixes this panic issue.

Font work un Mojave 10.14.1 with clover

**Comment by sarthakaditya52** [comment]
> https://xsggx.xiaosg.workers.dev/AR9565/ar9565%E8%93%9D%E7%89%99%E9%A9%B1%E5%8A%A8.zip
> 
> This version of the kext fixes this panic issue.

KP issue is gone with this but bluetooth doesn't work

**Comment by zxystd** [comment]
@sarthakaditya52 any logs? you can get the logs using following command:
```
log show --last boot | grep "Ath3kBT"
```

**Comment by sarthakaditya52** [comment]
> @sarthakaditya52 any logs? you can get the logs using following command:
> 
> ```
> log show --last boot | grep "Ath3kBT"
> ```

This is what I'm getting by running this command
![Screen Shot 2020-11-13 at 10 40 23 PM](https://user-images.githubusercontent.com/41894477/99100205-84d05280-2601-11eb-9c42-c95266e9be2e.png)

My device is AR3011 with VID: 0489 and PID: E027 and I've added them in both kexts (attached)
[Ath3kBT.zip](https://github.com/zxystd/AthBluetoothFirmware/files/5538304/Ath3kBT.zip)

**Comment by lynxnu** [comment]
I did a test with several people (about 30), many were successful with Catalina and Big Sur, but nobody has done it in Mojave|High Sierra and Sierra so far. maybe it can be a IOUSBHostFamily issue in these versions... @zxystd

**Comment by sarthakaditya52** [comment]
@lynxnu I've tried v1.0.1 that you've released but sadly I'm still getting a kernel panic, I'm on big sur 
![Screen Shot 2020-11-14 at 11 50 31 PM](https://user-images.githubusercontent.com/41894477/99154318-cf6ecf00-26d4-11eb-86bb-b9999d484e53.png)
Is there something that I might be doing wrong ?

**Comment by lynxnu** [comment]
@sarthakaditya52 This is a problem with kext itself. I tried to put the target system as 10.12, I believe that is the problem. Try again with another that I released, several users were successful.

**Comment by sarthakaditya52** [comment]
> @sarthakaditya52 This is a problem with kext itself. I tried to put the target system as 10.12, I believe that is causing the kernel panic. Try again with another that I released, several users were successful.

I was able to boot with v1.0.1-10.15+ but again bluetooth is not working, there's no bluetooth device found in the system report

**Comment by DaxSosa** [comment]
**Last login: Sun Nov 15 12:24:05 on console
MacBook-Pro:~ daxsosa$ log show --last boot | grep "Ath3kBT"
2020-11-15 12:22:13.812743-0600 0x65       Default     0x0                  0      0    kernel: Notice - new kext com.zxystd.Ath3kBTInjector, v1.0 matches prelinked kext but can't determine if executables are the same (no UUIDs).
2020-11-15 12:22:14.701461-0600 0x16b      Default     0x0                  0      0    kernel: kxld[com.zxystd.Ath3kBT]: The super class vtable '__ZTV9IOService' for vtable '__ZTV16AtherosFWService' is out of date. Make sure your kext has been built against the correct headers.
2020-11-15 12:22:14.701490-0600 0x16b      Default     0x0                  0      0    kernel: kxld[com.zxystd.Ath3kBT]: The __ZTV7Ath3kBT was not patched because its parent, the __ZTV16AtherosFWService, was not patchable.
2020-11-15 12:22:14.703657-0600 0x16b      Default     0x0                  0      0    kernel: Can't load kext com.zxystd.Ath3kBT - link failed.
2020-11-15 12:22:14.703920-0600 0x16b      Default     0x0                  0      0    kernel: Failed to load executable for kext com.zxystd.Ath3kBT.
2020-11-15 12:22:14.703969-0600 0x16b      Default     0x0                  0      0    kernel: Kext com.zxystd.Ath3kBT failed to load (0xdc008016).
2020-11-15 12:22:14.703976-0600 0x16b      Default     0x0                  0      0    kernel: Failed to load kext com.zxystd.Ath3kBT (error 0xdc008016).
2020-11-15 12:22:14.712819-0600 0x16b      Default     0x0                  0      0    kernel: Couldn't alloc class "Ath3kBT"
2020-11-15 12:23:11.355416-0600 0x204      Error       0x0                  46     0    kextd: (IOKit) [com.apple.kext:kextlog] Kext with invalid signatured (-67062) allowed: <OSKext 0x7fa7c0430de0 [0x7fff918678f0]> { URL = "file:///System/Library/Extensions/Ath3kBT.kext/", ID = "com.zxystd.Ath3kBT" }
2020-11-15 12:23:11.953100-0600 0x204      Default     0x0                  0      0    kernel: kxld[com.zxystd.Ath3kBT]: The super class vtable '__ZTV9IOService' for vtable '__ZTV16AtherosFWService' is out of date. Make sure your kext has been built against the correct headers.
2020-11-15 12:23:11.953117-0600 0x204      Default     0x0                  0      0    kernel: kxld[com.zxystd.Ath3kBT]: The __ZTV7Ath3kBT was not patched because its parent, the __ZTV16AtherosFWService, was not patchable.
2020-11-15 12:23:11.954013-0600 0x204      Default     0x0                  0      0    kernel: Can't load kext com.zxystd.Ath3kBT - link failed.
2020-11-15 12:23:11.954092-0600 0x204      Default     0x0                  0      0    kernel: Failed to load executable for kext com.zxystd.Ath3kBT.
2020-11-15 12:23:11.954120-0600 0x204      Default     0x0                  0      0    kernel: Kext com.zxystd.Ath3kBT failed to load (0xdc008016).
2020-11-15 12:23:11.954124-0600 0x204      Default     0x0                  0      0    kernel: Failed to load kext com.zxystd.Ath3kBT (error 0xdc008016).
2020-11-15 12:23:11.956760-0600 0x204      Error       0x0                  46     0    kextd: (IOKit) [com.apple.kext:kextlog] Failed to load /System/Library/Extensions/Ath3kBT.kext - (libkern/kext) link error.
2020-11-15 12:23:11.958636-0600 0x204      Error       0x0                  46     0    kextd: (IOKit) [com.apple.kext:kextlog] Load com.zxystd.Ath3kBT failed; removing personalities from kernel.
MacBook-Pro:~ daxsosa$** 

this is my last boot login, mojave 10.14.1

**Comment by lynxnu** [comment]
> > @sarthakaditya52 This is a problem with kext itself. I tried to put the target system as 10.12, I believe that is causing the kernel panic. Try again with another that I released, several users were successful.
> 
> I was able to boot with v1.0.1-10.15+ but again bluetooth is not working, there's no bluetooth device found in the system report

Inject your Bluetooth with USBInjectAll, and do a USB Map with Hackintool.

**Comment by sarthakaditya52** [comment]
> Inject your Bluetooth with USBInjectAll, and do a USB Map with Hackintool.
I've done that...still getting I can't get any bluetooth device...if I boot without this kext then I do get a bluetooth device but the firmware is unknown so it doesn't work either 😐

**Comment by sarthakaditya52** [comment]
Welp...I've tried everything that I can but I still don't have a bluetooth device and the bluetooth shows up as BroadcomBluetoothHostControllerUSBTransport when I'm using USBMap tool
![Screen Shot 2020-11-24 at 12 14 15 PM](https://user-images.githubusercontent.com/41894477/100058189-e472fd00-2e4e-11eb-9071-f983a35a06bd.png)
Without the injector it shows up as something else so I guess the injector is also working.

**Comment by andreamaral-as** [comment]
Hello everyone and in particular @lynxnu,

I'm running Big Sur with the kexts properly added and even then the firmware is not loaded according to Hackintool.

When running this (log show --last boot | grep "Ath3kBT") nothing is returned.
My notebook is an Acer E5-571G-760Q with Atheros AR3012 bluetooth. The USB ports are properly mapped with Hackintool.

People who were successful in activating bluetooh could kindly describe what procedures / commands they performed on the MacOS post installation. I would like to reproduce the post installation step-by-step to conclude if it is any configuration adjustment that is preventing the bluetooth to work.

General setup:
MacOS Big Sur: 11.0.1 (20B29)
opencore 063 RELEASE
Kext Ath3kBT-1.0.1-RELEASE.zip from the lynxnu repository.

Best regards,
André

PS. Using Google translate

**Comment by cwr31** [comment]
can ar9462/ar5b22 work with your kexts? this is a 5G card,wifi is good now,but BT can't work

**Comment by Ferbez** [comment]
@sarthakaditya52 and everyone else who tries to get AR3011 to work in 10.14+ should get new IOath3kfrmwr.kext [here](https://github.com/Ferbez/OS-X-Atheros-3k-Firmware)

**Comment by DaxSosa** [comment]
> @sarthakaditya52 and everyone else who tries to get AR3011 to work in 10.14+ should get new IOath3kfrmwr.kext [here](https://github.com/Ferbez/OS-X-Atheros-3k-Firmware)

signature error. mojave 10.14.1 clover

**Comment by Ferbez** [comment]
> > @sarthakaditya52 and everyone else who tries to get AR3011 to work in 10.14+ should get new IOath3kfrmwr.kext [here](https://github.com/Ferbez/OS-X-Atheros-3k-Firmware)
> 
> signature error. mojave 10.14.1 clover

How did you installed it? Have you disabled SIP? And yes, I suggest you should switch to OpenCore

**Comment by Ferbez** [comment]
> > @sarthakaditya52 and everyone else who tries to get AR3011 to work in 10.14+ should get new IOath3kfrmwr.kext [here](https://github.com/Ferbez/OS-X-Atheros-3k-Firmware)
> 
> signature error. mojave 10.14.1 clover

Give more info about how you installed it and did you disabled SIP [here](https://github.com/Ferbez/OS-X-Atheros-3k-Firmware/issues)

**Comment by zxystd** [comment]
fix in 1.1.0, you can try to use it.
